# Generated by Django 3.2.13 on 2022-05-18 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paeuser',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sistema_pae.career'),
        ),
        migrations.AlterField(
            model_name='paeuser',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
