# Generated by Django 4.0.3 on 2022-06-08 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='AnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('answer', models.FileField(upload_to='')),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pae.question')),
                ('id_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_answer_file', to='sistema_pae.paeuser')),
                ('id_tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_pae.paeuser')),
            ],
        ),
    ]
