# Generated by Django 4.0.3 on 2022-04-27 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema_pae', '0002_alter_subject_tutors'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='UserPae',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('user_type', models.IntegerField()),
                ('status', models.IntegerField()),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sistema_pae.career')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='id_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_answer', to='sistema_pae.userpae'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id_tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_pae.userpae'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pae.userpae'),
        ),
        migrations.AlterField(
            model_name='session',
            name='id_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_student', to='sistema_pae.userpae'),
        ),
        migrations.AlterField(
            model_name='session',
            name='id_tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_pae.userpae'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='tutors',
            field=models.ManyToManyField(blank=True, to='sistema_pae.userpae'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
