# Generated by Django 4.0.3 on 2022-06-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pae', '0002_alter_answer_answer_answerfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerfile',
            old_name='answer',
            new_name='file',
        ),
    ]
