# Generated by Django 4.0.3 on 2022-04-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pae', '0003_alter_subject_unique_together_userpae_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='id_career',
        ),
        migrations.AddField(
            model_name='subject',
            name='id_career',
            field=models.ManyToManyField(blank=True, to='sistema_pae.career'),
        ),
    ]
