# Generated by Django 4.0.3 on 2022-04-28 00:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema_pae', '0004_remove_subject_id_career_subject_id_career'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPae',
            new_name='PaeUser',
        ),
    ]
