# Generated by Django 4.0.3 on 2022-04-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pae', '0006_remove_paeuser_id_alter_paeuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paeuser',
            old_name='user',
            new_name='id',
        ),
    ]
