# Generated by Django 4.0.3 on 2022-04-28 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pae', '0007_rename_user_paeuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='tutors',
        ),
        migrations.CreateModel(
            name='TutorSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pae.subject')),
                ('id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_pae.paeuser')),
            ],
        ),
    ]
